"""Terminal preview and human confirmation helpers."""

from __future__ import annotations

from typing import Literal

from models import Contact, EmailDraft


Action = Literal["send", "draft", "skip"]
_ACTION_ALIASES: dict[str, Action] = {
    "send": "send",
    "s": "send",
    "draft": "draft",
    "d": "draft",
    "skip": "skip",
    "k": "skip",
}


def preview_email(draft: EmailDraft, contact: Contact) -> None:
    """Print the complete, reviewable email before the user chooses an action."""
    print("\n" + "=" * 72)
    print("EMAIL PREVIEW")
    print("=" * 72)
    print(f"Recipient: {contact.recipient_name or 'Unknown'} <{contact.recipient_email}>")
    print(f"Company: {contact.company}")
    print(f"Role: {contact.role}")
    print(f"Subject: {draft.subject}")
    print(f"Generated by: {draft.source}")
    print("-" * 72)
    print(draft.body)
    print("-" * 72)

    if draft.word_limit_exceeded or draft.word_count > 150:
        print(f"WARNING: Word count: {draft.word_count} (over the 150-word limit)")
    else:
        print(f"Word count: {draft.word_count}")
    if draft.generic_hook:
        print(
            "WARNING: The personalization hook is generic. Add a company or role "
            "detail before confirming delivery."
        )
    print("=" * 72)


def choose_subject(draft: EmailDraft) -> str:
    """Let the operator pick among suggested subject lines (Phase 8 stretch).

    Returns the current subject unchanged when there is only one option or when
    input is unavailable, so non-interactive runs stay deterministic.
    """
    options = draft.subject_options or [draft.subject]
    if len(options) <= 1:
        return draft.subject

    print("\nSubject options:")
    for index, option in enumerate(options, start=1):
        marker = " (current)" if option == draft.subject else ""
        print(f"  {index}. {option}{marker}")

    while True:
        try:
            response = input(
                f"Choose a subject [1-{len(options)}] (Enter to keep current): "
            ).strip()
        except EOFError:
            return draft.subject
        if not response:
            return draft.subject
        if response.isdigit() and 1 <= int(response) <= len(options):
            return options[int(response) - 1]
        print(f"Invalid choice. Enter a number from 1 to {len(options)}.")


def prompt_action() -> Action:
    """Require an explicit send, draft, or skip decision before progressing."""
    while True:
        try:
            response = input("Choose an action [send/draft/skip] (s/d/k): ").strip().lower()
        except EOFError:
            print("\nNo action received; skipping this email for safety.")
            return "skip"

        action = _ACTION_ALIASES.get(response)
        if action:
            return action
        print("Invalid action. Enter send (s), draft (d), or skip (k).")
