import type {
  Confidence,
  MatchScore,
  TailoringRun,
} from "@/lib/schemas";
import { escapeHtml } from "@/lib/pdf/escape";
import { PdfError } from "@/lib/pdf/errors";

const DISCLAIMER =
  "Generated by JobPilot. All content is a draft derived from your resume — verify every claim before submitting. No ATS outcome is guaranteed. Do not submit unreviewed output.";

/* ------------------------------------------------------------------ */
/* Context types (pure data — unit-tested)                             */
/* ------------------------------------------------------------------ */

export interface ComparisonBullet {
  original: string;
  tailored: string;
  changed: boolean;
  confidence: Confidence;
  keywordsAddressed: string[];
  riskFlag?: string;
}

export interface ComparisonRole {
  company: string;
  title: string;
  bullets: ComparisonBullet[];
}

export interface ComparisonContext {
  jobTitle: string;
  company: string;
  date: string;
  original: MatchScore;
  tailored: MatchScore;
  scoreDelta: number;
  requiredSkills: string[];
  keywords: string[];
  roles: ComparisonRole[];
  gaps: TailoringRun["gapAnalysis"]["gaps"];
  warnings: string[];
}

/** Assert the run is tailored and return the non-null tailored fields. */
function requireTailored(run: TailoringRun) {
  if (!run.tailoredResume || !run.tailoredMatch) {
    throw new PdfError(
      "PDF_NOT_TAILORED",
      "This run has no tailored resume yet. Tailor before exporting.",
    );
  }
  return { tailoredResume: run.tailoredResume, tailoredMatch: run.tailoredMatch };
}

function formatDate(iso: string): string {
  const d = new Date(iso);
  return Number.isNaN(d.getTime())
    ? iso
    : d.toLocaleDateString("en-US", {
        year: "numeric",
        month: "short",
        day: "numeric",
      });
}

/** TailoringRun → structured context for the comparison PDF. */
export function buildComparisonContext(run: TailoringRun): ComparisonContext {
  const { tailoredResume, tailoredMatch } = requireTailored(run);

  const roles: ComparisonRole[] = tailoredResume.tailoredExperience.map(
    (role) => ({
      company: role.company,
      title: role.title,
      bullets: role.bullets.map((b) => ({
        original: b.original,
        tailored: b.tailored,
        changed: b.original.trim() !== b.tailored.trim(),
        confidence: b.confidence,
        keywordsAddressed: b.keywordsAddressed,
        riskFlag: b.riskFlag,
      })),
    }),
  );

  return {
    jobTitle: run.jobDescription.jobTitle,
    company: run.jobDescription.company ?? "",
    date: formatDate(run.createdAt),
    original: run.originalMatch,
    tailored: tailoredMatch,
    scoreDelta: tailoredMatch.overallScore - run.originalMatch.overallScore,
    requiredSkills: run.jobDescription.requiredSkills,
    keywords: run.jobDescription.keywords,
    roles,
    gaps: run.gapAnalysis.gaps.filter((g) => g.importance !== "low"),
    warnings: run.warnings,
  };
}

/* ------------------------------------------------------------------ */
/* Shared print CSS                                                    */
/* ------------------------------------------------------------------ */

const BASE_CSS = `
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; }
  body {
    font-family: -apple-system, "Segoe UI", Helvetica, Arial, sans-serif;
    color: #0f172a; font-size: 11px; line-height: 1.45;
  }
  h1 { font-size: 20px; margin: 0 0 2px; }
  h2 { font-size: 13px; margin: 18px 0 6px; padding-bottom: 3px;
       border-bottom: 1px solid #e2e8f0; text-transform: uppercase;
       letter-spacing: .04em; color: #334155; }
  .muted { color: #64748b; }
  .chip { display: inline-block; padding: 1px 7px; border-radius: 999px;
          background: #eef2ff; color: #3730a3; font-size: 9px; margin: 0 3px 3px 0; }
  mark { background: #fef9c3; padding: 0 2px; border-radius: 2px; }
  .disclaimer { margin-top: 20px; padding-top: 8px; border-top: 1px solid #e2e8f0;
                color: #64748b; font-size: 8.5px; }
  @page { size: A4; margin: 16mm 14mm; }
`;

function htmlDoc(title: string, extraCss: string, body: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(
    title,
  )}</title><style>${BASE_CSS}${extraCss}</style></head><body>${body}</body></html>`;
}

function chips(items: string[]): string {
  return items.map((i) => `<span class="chip">${escapeHtml(i)}</span>`).join("");
}

function confColor(c: Confidence): string {
  return c === "high" ? "#16a34a" : c === "medium" ? "#d97706" : "#dc2626";
}

/* ------------------------------------------------------------------ */
/* Comparison PDF (the portfolio proof artifact)                       */
/* ------------------------------------------------------------------ */

export function renderComparisonHtml(run: TailoringRun): string {
  const ctx = buildComparisonContext(run);
  const deltaSign = ctx.scoreDelta >= 0 ? "+" : "";

  const scoreBlock = `
    <div class="scores">
      <div class="score"><div class="num">${Math.round(
        ctx.original.overallScore,
      )}</div><div class="lbl">Original</div></div>
      <div class="arrow">→</div>
      <div class="score"><div class="num tailored">${Math.round(
        ctx.tailored.overallScore,
      )}</div><div class="lbl">Tailored</div></div>
      <div class="delta">${deltaSign}${ctx.scoreDelta} pts</div>
    </div>
    <p class="muted">${escapeHtml(ctx.tailored.explanation)}</p>`;

  const bulletRows = ctx.roles
    .map((role) => {
      const rows = role.bullets
        .map((b) => {
          const tailored = b.changed
            ? `<mark>${escapeHtml(b.tailored)}</mark>`
            : escapeHtml(b.tailored);
          const risk = b.riskFlag
            ? `<div class="risk">⚠ ${escapeHtml(b.riskFlag)}</div>`
            : "";
          return `<tr>
            <td class="orig">${escapeHtml(b.original)}</td>
            <td class="tail">${tailored}
              <div class="meta"><span style="color:${confColor(
                b.confidence,
              )}">${b.confidence}</span>${
                b.keywordsAddressed.length
                  ? " · " + escapeHtml(b.keywordsAddressed.join(", "))
                  : ""
              }</div>${risk}</td>
          </tr>`;
        })
        .join("");
      return `<tr class="role"><td colspan="2">${escapeHtml(
        role.title,
      )} — ${escapeHtml(role.company)}</td></tr>${rows}`;
    })
    .join("");

  const gapRows = ctx.gaps.length
    ? ctx.gaps
        .map(
          (g) => `<tr>
            <td>${escapeHtml(g.name)}</td>
            <td>${escapeHtml(g.importance)}</td>
            <td>${escapeHtml(g.suggestedAction)}</td>
          </tr>`,
        )
        .join("")
    : `<tr><td colspan="3" class="muted">No high or medium gaps.</td></tr>`;

  const extraCss = `
    .scores { display: flex; align-items: center; gap: 14px; margin: 6px 0; }
    .score { text-align: center; }
    .score .num { font-size: 26px; font-weight: 700; }
    .score .num.tailored { color: #16a34a; }
    .score .lbl { font-size: 8px; text-transform: uppercase; color: #64748b; }
    .arrow { font-size: 18px; color: #94a3b8; }
    .delta { background: #dcfce7; color: #166534; padding: 2px 8px;
             border-radius: 999px; font-weight: 600; font-size: 10px; }
    table { width: 100%; border-collapse: collapse; table-layout: fixed; }
    td { vertical-align: top; padding: 5px 6px; border-bottom: 1px solid #eef2f6;
         word-wrap: break-word; }
    tr.role td { background: #f8fafc; font-weight: 600; color: #334155;
                 border-bottom: 1px solid #e2e8f0; }
    td.orig { width: 50%; color: #64748b; }
    td.tail { width: 50%; }
    .meta { font-size: 8.5px; color: #64748b; margin-top: 2px; }
    .risk { font-size: 8.5px; color: #b45309; margin-top: 2px; }
    .gaps td { border-bottom: 1px solid #eef2f6; }
    .gaps th { text-align: left; font-size: 9px; text-transform: uppercase;
               color: #64748b; padding: 4px 6px; border-bottom: 1px solid #e2e8f0; }`;

  const warnings = ctx.warnings.length
    ? `<div class="warn">${ctx.warnings
        .map((w) => `• ${escapeHtml(w)}`)
        .join("<br>")}</div>`
    : "";

  const body = `
    <h1>${escapeHtml(ctx.jobTitle)}</h1>
    <div class="muted">${escapeHtml(
      [ctx.company, ctx.date].filter(Boolean).join(" · "),
    )}</div>

    <h2>Match Score</h2>
    ${scoreBlock}

    <h2>Target Requirements</h2>
    <div><strong>Required:</strong> ${chips(ctx.requiredSkills) || "—"}</div>
    <div style="margin-top:4px"><strong>Keywords:</strong> ${
      chips(ctx.keywords) || "—"
    }</div>

    <h2>Bullet-by-Bullet Comparison</h2>
    <table><tbody>
      <tr class="role"><td class="orig">Original</td><td class="tail">Tailored</td></tr>
      ${bulletRows}
    </tbody></table>

    <h2>Remaining Gaps</h2>
    <table class="gaps"><thead><tr><th>Requirement</th><th>Importance</th><th>Suggested action</th></tr></thead>
    <tbody>${gapRows}</tbody></table>
    ${warnings ? `<h2>Before You Submit</h2>${warnings}` : ""}

    <div class="disclaimer">${escapeHtml(DISCLAIMER)}</div>`;

  return htmlDoc(`Comparison — ${ctx.jobTitle}`, extraCss, body);
}

/* ------------------------------------------------------------------ */
/* Tailored resume PDF (clean, single-column, ATS-friendly)            */
/* ------------------------------------------------------------------ */

export function renderTailoredResumeHtml(run: TailoringRun): string {
  const { tailoredResume } = requireTailored(run);
  const { resume, jobDescription } = run;
  const c = resume.contact;

  const contactLine = [c.email, c.phone, c.location, ...c.links]
    .filter(Boolean)
    .map((x) => escapeHtml(x as string))
    .join(" · ");

  const skills = tailoredResume.tailoredSkills.length
    ? tailoredResume.tailoredSkills
    : resume.skills;

  const experience = tailoredResume.tailoredExperience
    .map((role) => {
      const bullets = role.bullets
        .map((b) => `<li>${escapeHtml(b.tailored)}</li>`)
        .join("");
      return `<div class="role">
        <div class="role-head"><strong>${escapeHtml(
          role.title,
        )}</strong>, ${escapeHtml(role.company)}</div>
        <ul>${bullets}</ul>
      </div>`;
    })
    .join("");

  const education = resume.education
    .map(
      (e) =>
        `<div>${escapeHtml(
          [e.degree, e.field].filter(Boolean).join(" in "),
        )}${e.degree || e.field ? " — " : ""}${escapeHtml(e.institution)}${
          e.endDate ? ` <span class="muted">(${escapeHtml(e.endDate)})</span>` : ""
        }</div>`,
    )
    .join("");

  const certs = resume.certifications
    .map((cert) => `<li>${escapeHtml(cert.name)}</li>`)
    .join("");

  const extraCss = `
    h1 { text-align: center; }
    .contact { text-align: center; margin-bottom: 6px; }
    ul { margin: 3px 0 8px; padding-left: 16px; }
    li { margin-bottom: 2px; }
    .role { margin-bottom: 8px; }
    .role-head { margin-bottom: 2px; }
    .skills span { margin-right: 6px; }`;

  const body = `
    <h1>${escapeHtml(c.name)}</h1>
    <div class="contact muted">${contactLine}</div>
    ${
      tailoredResume.tailoredSummary
        ? `<h2>Summary</h2><div>${escapeHtml(tailoredResume.tailoredSummary)}</div>`
        : ""
    }
    <h2>Skills</h2>
    <div class="skills">${skills.map((s) => escapeHtml(s)).join(" · ")}</div>
    <h2>Experience</h2>
    ${experience}
    ${education ? `<h2>Education</h2>${education}` : ""}
    ${certs ? `<h2>Certifications</h2><ul>${certs}</ul>` : ""}
    <div class="disclaimer">Tailored for: ${escapeHtml(
      jobDescription.jobTitle,
    )}. ${escapeHtml(DISCLAIMER)}</div>`;

  return htmlDoc(`${c.name} — Resume`, extraCss, body);
}
