/**
 * Object storage adapter (P1.2.2) — resumes and generated PDFs.
 *
 * Two drivers behind one interface:
 *   fs  local development and tests. No MinIO required, so `npm test` works
 *       on a laptop with nothing running.
 *   s3  MinIO locally (docker-compose), any S3-compatible service in prod.
 *
 * Selected by STORAGE_DRIVER, defaulting to `fs` — the driver that cannot
 * silently talk to a real bucket.
 *
 * EC-P1-18: keys are OPAQUE and generated here. The client filename is never
 * part of a key — it is stored separately as a display-only column. A key built
 * from user input is a path-traversal bug waiting to happen
 * (`../../etc/passwd`, unicode RTL overrides, and so on).
 *
 * EC-P1-25: the ORDER of operations matters and lives in the caller, not here.
 * Write the DB row first (status pending), then the object, then mark ready. A
 * failed upload leaves a pending row a reaper can find; the reverse order leaks
 * storage forever with nothing pointing at it.
 */

import { randomUUID } from "node:crypto";
import { mkdir, readFile, writeFile, unlink } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

export interface ObjectStore {
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
}

/** Opaque, collision-free, and carrying no user-controlled path segment. */
export function newObjectKey(userId: string, kind: "resume" | "pdf", ext: string): string {
  const safeExt = ext.replace(/[^a-z0-9]/gi, "").slice(0, 8) || "bin";
  return `${kind}/${userId}/${randomUUID()}.${safeExt}`;
}

/* ------------------------------------------------------------------ */
/* fs driver                                                           */
/* ------------------------------------------------------------------ */

class FsObjectStore implements ObjectStore {
  constructor(private readonly root: string) {}

  private path(key: string): string {
    // Defence in depth. Keys are generated by newObjectKey() and are already
    // safe, but a future caller might pass something else — so resolve and
    // confirm the result is still inside the root before touching disk.
    const full = resolve(join(this.root, key));
    if (!full.startsWith(resolve(this.root) + "/")) {
      throw new Error(`Refusing to write outside the storage root: ${key}`);
    }
    return full;
  }

  async put(key: string, body: Buffer): Promise<void> {
    const full = this.path(key);
    await mkdir(dirname(full), { recursive: true });
    await writeFile(full, body);
  }

  async get(key: string): Promise<Buffer> {
    return readFile(this.path(key));
  }

  async delete(key: string): Promise<void> {
    await unlink(this.path(key)).catch((e: NodeJS.ErrnoException) => {
      if (e.code !== "ENOENT") throw e;   // deleting twice is not an error
    });
  }
}

/* ------------------------------------------------------------------ */
/* s3 driver                                                           */
/* ------------------------------------------------------------------ */

class S3ObjectStore implements ObjectStore {
  private client: unknown;

  private async sdk() {
    if (!this.client) {
      // Imported lazily so the fs driver — and therefore the test suite — has
      // no dependency on the AWS SDK being installed.
      const { S3Client } = await import("@aws-sdk/client-s3");
      this.client = new S3Client({
        region: process.env.AWS_REGION ?? "us-east-1",
        endpoint: process.env.S3_ENDPOINT,
        forcePathStyle: true,          // MinIO requires path-style addressing
        credentials: {
          accessKeyId: process.env.S3_ACCESS_KEY ?? "",
          secretAccessKey: process.env.S3_SECRET_KEY ?? "",
        },
      });
    }
    return this.client as import("@aws-sdk/client-s3").S3Client;
  }

  private get bucket(): string {
    const b = process.env.STORAGE_BUCKET;
    if (!b) throw new Error("STORAGE_BUCKET is not set.");
    return b;
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    const { PutObjectCommand } = await import("@aws-sdk/client-s3");
    const c = await this.sdk();
    await c.send(new PutObjectCommand({
      Bucket: this.bucket, Key: key, Body: body, ContentType: contentType,
    }));
  }

  async get(key: string): Promise<Buffer> {
    const { GetObjectCommand } = await import("@aws-sdk/client-s3");
    const c = await this.sdk();
    const r = await c.send(new GetObjectCommand({ Bucket: this.bucket, Key: key }));
    return Buffer.from(await r.Body!.transformToByteArray());
  }

  async delete(key: string): Promise<void> {
    const { DeleteObjectCommand } = await import("@aws-sdk/client-s3");
    const c = await this.sdk();
    await c.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: key }));
  }
}

/* ------------------------------------------------------------------ */

let instance: ObjectStore | undefined;

export function objectStore(): ObjectStore {
  if (!instance) {
    instance = process.env.STORAGE_DRIVER === "s3"
      ? new S3ObjectStore()
      : new FsObjectStore(process.env.STORAGE_FS_ROOT ?? ".storage");
  }
  return instance;
}

/** Test seam. */
export function __setObjectStore(s: ObjectStore | undefined): void {
  instance = s;
}
